### ISSUE TITLE
API spec

### ISSUE THREAD

**Issue by barnabasJ** [sunndeath/elixir-phoenix-graphql-react-realworld-example-app#4]
Hi @sunndeath like I said over at the realworld repo, I'm also working on an elixir implementation and was wondering if you already decided on a structure for GraphqL API/Types. If not we could maybe collobarate on that, or if you already found a structure that works for you, if you would mind sharing?

**Comment by sunndeath** [comment]
Hi @barnabasJ!
Unfortunately, I haven't schema, because I have no experience in GraphQL. And I encountered problems and I will solve them gradually.
